# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be0cf80f7d809435f4547ae96133597ea9289273499d69d1f40e4811b988e893b20490348f7de2f56ea30667acb0affe5d698ae69aa4d06f8b037aead718f710

test:
  secret_key_base: a256f09e2e5aa494848b7f13b198baf1112d8f0262f11c5b931eea486492780e8cbb404a3803297ebd4fd30e6311e741335b5646da92edc3362c1269c785ba24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
